# Generated by Django 3.2.12 on 2022-02-17 11:36

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='Телефон')),
                ('code', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
                ('tag', models.CharField(max_length=10, verbose_name='тег')),
                ('tz', models.CharField(default='3', max_length=3, null=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Часовой пояс')),
            ],
        ),
        migrations.CreateModel(
            name='Send_out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время запуска рассылки')),
                ('filter_code', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3)])),
                ('filter_tag', models.CharField(max_length=10, verbose_name='тег')),
                ('text_msg', models.TextField(max_length=5000, verbose_name='текст рассылки')),
                ('end', models.DateTimeField(default=datetime.datetime(2022, 2, 17, 12, 36, 1, 324191, tzinfo=utc), verbose_name='дата и время завершения рассылки')),
            ],
        ),
        migrations.CreateModel(
            name='MessageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(verbose_name='Дата cоздания')),
                ('status', models.BooleanField(default=False, verbose_name='статус отправки')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_client_id', to='sender.client')),
                ('send_out_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_send_out_id', to='sender.send_out')),
            ],
        ),
    ]
