# Generated by Django 4.0.2 on 2022-02-11 12:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageinfo',
            name='create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата cоздания'),
        ),
        migrations.AlterField(
            model_name='send_out',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 11, 13, 59, 12, 928325, tzinfo=utc), verbose_name='дата и время завершения рассылки'),
        ),
    ]
