# Generated by Django 4.0.2 on 2022-02-12 10:21

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0007_alter_send_out_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='send_out',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 12, 11, 21, 19, 937411, tzinfo=utc), verbose_name='дата и время завершения рассылки'),
        ),
    ]
