# Generated by Django 4.0.2 on 2022-02-12 10:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0008_alter_client_phone_number_alter_send_out_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send_out',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 12, 11, 21, 33, 318772, tzinfo=utc), verbose_name='дата и время завершения рассылки'),
        ),
    ]
