# Generated by Django 4.0.2 on 2022-02-12 17:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0009_alter_send_out_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageinfo',
            name='status',
            field=models.BooleanField(default=False, verbose_name='статус отправки'),
        ),
        migrations.AlterField(
            model_name='send_out',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 12, 18, 10, 12, 451823, tzinfo=utc), verbose_name='дата и время завершения рассылки'),
        ),
    ]
